micro-ui/web/src/App.js
micro-ui/web/src/index.js

Card fix in deployment

---

micro-ui/web/micro-ui-internals/example/public/index.html
micro-ui/web/micro-ui-internals/packages/css/package.json
micro-ui/web/micro-ui-internals/packages/css/src/components/microplanning.scss
micro-ui/web/micro-ui-internals/packages/modules/hcm-microplanning/package.json
micro-ui/web/micro-ui-internals/packages/modules/hcm-microplanning/src/components/Nagivator.js
micro-ui/web/micro-ui-internals/packages/modules/hcm-microplanning/src/components/resourceMapping.js
micro-ui/web/micro-ui-internals/packages/modules/hcm-microplanning/src/configs/BaseMapLayers.json
micro-ui/web/micro-ui-internals/packages/modules/hcm-microplanning/src/configs/timeLineOptions.json
micro-ui/web/micro-ui-internals/packages/modules/hcm-microplanning/src/pages/employee/CreateMicroplan.js
micro-ui/web/micro-ui-internals/packages/modules/hcm-microplanning/src/pages/employee/Hypothesis.js
micro-ui/web/micro-ui-internals/packages/modules/hcm-microplanning/src/pages/employee/Mapping.js
micro-ui/web/micro-ui-internals/packages/modules/hcm-microplanning/src/pages/employee/RuleEngine.js
micro-ui/web/micro-ui-internals/packages/modules/hcm-microplanning/src/pages/employee/Upload.js
micro-ui/web/public/index.html

HLM-5148 adding mapping

---

micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/components/CampaignSummary.js
micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/SetupCampaign.js

- **summary to back screen redirection fix**
- **preview params fix**

summary back fix

---

micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/components/CampaignSummary.js

Start end End date updated...
"@egovernments/digit-ui-components": "0.0.2-beta.19", used

Start end End date updated

---

micro-ui/web/micro-ui-internals/packages/modules/hrms/src/components/pageComponents/assignment.js
micro-ui/web/micro-ui-internals/packages/modules/hrms/src/components/pageComponents/jurisdiction.js
micro-ui/web/micro-ui-internals/packages/modules/hrms/src/pages/createEmployee.js

hrms changes

---

health/micro-ui/web/micro-ui-internals/example/public/index.html
health/micro-ui/web/micro-ui-internals/packages/css/package.json
health/micro-ui/web/public/index.html

css version update

---

micro-ui/web/workbench/package.json

updated core version

---

health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/UserAccessMgmtTableWrapper.js

User Access Management Summary- Null Check validation added

---

health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/PlanInbox.js

fix blank row

---

micro-ui/web/micro-ui-internals/packages/modules/workbench/src/pages/employee/index.js
micro-ui/web/micro-ui-internals/packages/react-components/src/atoms/BreadCrumb.js

UCEM-765 : home redirection fix test

---

micro-ui/web/micro-ui-internals/packages/modules/workbench/package.json

UCEM-765 : Updated breadcrumb

---

health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/securityPopUp.js

added localisation for security question label

---

health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/PopInbox.js

fixed wrong action in workflow

---

health/micro-ui/web/micro-ui-internals/example/public/index.html
health/micro-ui/web/micro-ui-internals/example/src/UICustomizations.js
health/micro-ui/web/micro-ui-internals/packages/css/package.json
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/configs/MicroplanSearchConfig.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/configs/MyMicroplanSearchConfig.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/configs/UICustomizations.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/hooks/services/searchSavedPlans.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/hooks/services/searchSavedPlansWithCampaign.js
health/micro-ui/web/public/index.html

My microplan data fixes, localisation fixes

---

health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FormulaConfigWrapper.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/HypothesisWrapper.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/hooks/services/createUpdatePlanProject.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/SetupMicroplan.js

Invalidation logics of boundary, assumptions, formulas

---

health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/PlanInbox.js

Implemented Dynamic column for additiona fields, resources, security quest

---

health/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/index.scss
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FormulaConfigWrapper.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FormulaConfiguration.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/RoleTableComposer.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/TableSearchBar.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/UserAccess.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/UserAccessWrapper.js

updated formula configuration and user management css

---

health/micro-ui/web/micro-ui-internals/example/src/UICustomizations.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/configs/FacilityMappingConfig.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/configs/UICustomizations.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/FacilityCatchmentMapping.js

facility popup temp fix

---

health/micro-ui/web/micro-ui-internals/example/public/index.html
health/micro-ui/web/micro-ui-internals/packages/css/package.json
health/micro-ui/web/micro-ui-internals/packages/css/src/components/microplan.scss
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FacilityPopup.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/PopInboxTable.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/BreadCrumbNew.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/FacilityCatchmentMapping.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/PlanInbox.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/PopInbox.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/index.js
health/micro-ui/web/public/index.html

updated table selection styles and others

---

health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/components/BulkUpload.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/Hypothesis.js

updated xlsx icon

---

health/micro-ui/web/micro-ui-internals/example/public/index.html
health/micro-ui/web/micro-ui-internals/packages/css/package.json
health/micro-ui/web/micro-ui-internals/packages/css/src/components/microplanning.scss
health/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/formulaConfig.scss
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/components/BulkUpload.js
health/micro-ui/web/public/index.html

fixed assumption audit fixes

---

health/micro-ui/web/micro-ui-internals/example/package.json
health/micro-ui/web/micro-ui-internals/package.json
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/package.json
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/package.json
health/micro-ui/web/microplan/package.json
health/micro-ui/web/package.json
health/micro-ui/web/workbench/inter-package.json
health/micro-ui/web/workbench/package.json

Vesrion update

---

health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/UserAccess.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/hooks/services/SearchHRMSEmployeeConfig.js

user tagging fixes

---

health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/AssumptionsList.js

Assumptionlist fix

---

health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FacilityPopup.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/PopInboxTable.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/PlanInbox.js

reverted column freeze as it was causing issues

---

health/micro-ui/web/micro-ui-internals/packages/css/src/components/microplanning.scss
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/PopInboxTable.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/tableCustomStyle.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/PlanInbox.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/PopInbox.js

minor changes

---

health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/Hypothesis.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/HypothesisWrapper.js

assumptions fixes

---

health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/timelinePopUpWrapper.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/FacilityCatchmentMapping.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/PlanInbox.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/PopInbox.js

adhoc changes

---

health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FormulaConfiguration.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/Hypothesis.js

validations done for assumptions and formula

---

health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FormulaConfiguration.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/Hypothesis.js

removed alphanumeric valiadtion

---

health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/HypothesisWrapper.js

validation update

---

health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/HypothesisWrapper.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/SetupMicroplan.js

Fixed toast issue + fixed invalidation of assumption and formula

---

micro-ui/web/core/package.json
micro-ui/web/micro-ui-internals/example/package.json
micro-ui/web/micro-ui-internals/package.json
micro-ui/web/package.json

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

updated versions

---

health/micro-ui/web/micro-ui-internals/example/src/setupProxy.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/configs/UICustomizations.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/configs/attendance_inbox_config.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/pages/employee/attendance_inbox.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/pages/employee/index.js

HCM-1646::Payment inbox attendance

---

health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/Module.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/bill_inbox/BillInbox.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/bill_inbox/BillSearchBox.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/bill_inbox/billInboxTable.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/custom_comp/filter_section.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/sample.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/pages/employee/ViewAttendance.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/pages/employee/my_bills.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/services/PaymentsInitialization.js

Removed hardcoded boundaryType options
Fixed marked by and approvedBy field for campaign supervisor inbox

HCMPRE-1863:: Updated boundaryHierarchyOrder from boundary search.

---

health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/BoundaryComponent.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/attendanceManagementTable.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/attendance_inbox/table_inbox.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/bill_inbox/BillInbox.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/bill_inbox/billInboxTable.js

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

fixed gap and added click on row

---

health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/Module.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/appConfigurationScreen/DummyTry.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/index.js
health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/OldCampaignCard.js

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

dummy component added

---

health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/BoundaryComponent.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/MyBillsTable.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/attendanceManagementTable.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/attendance_inbox/attendance_inbox.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/attendance_inbox/filter_section.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/attendance_inbox/table_inbox.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/bill_inbox/BillInbox.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/bill_inbox/billInboxTable.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/bill_inbox/bill_boundary_filter.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/commentPopUp.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/pages/employee/ViewAttendance.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/utils/index.js

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

Added the view comment logic for payment

---

micro-ui/web/micro-ui-internals/example/package.json
micro-ui/web/micro-ui-internals/example/public/index.html
micro-ui/web/micro-ui-internals/packages/modules/sample/package.json
micro-ui/web/micro-ui-internals/packages/modules/sample/src/configs/SampleConfig.js
micro-ui/web/micro-ui-internals/packages/modules/sample/src/configs/uiComponentsConfigs/inboxConfig.js
micro-ui/web/micro-ui-internals/packages/modules/sample/src/configs/uiComponentsConfigs/searchConfig.js

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

Updated components version and added comments in the sample configs

---

health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/components/AppPreview.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/NewCampaignCreate/AppModule.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/appConfigurationRedesign/AppConfigurationParentLayer.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/appConfigurationRedesign/AppConfigurationWrapper.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/appConfigurationRedesign/AppFieldComposer.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/appConfigurationRedesign/AppFieldScreenWrapper.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/appConfigurationRedesign/DraggableField.js

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

FEATURE/HCMPRE-2816 :: Added feature to disable and enable app default fields

---

micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/sandbox.scss
micro-ui/web/micro-ui-internals/packages/modules/core/src/components/AppModules.js
micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/index.js
micro-ui/web/micro-ui-internals/packages/modules/sandbox/src/configs/UICustomizations.js
micro-ui/web/micro-ui-internals/packages/modules/sandbox/src/pages/employee/ProductDetails/ProductDetailsComponentUpdated.js
micro-ui/web/micro-ui-internals/packages/modules/sandbox/src/pages/employee/ProductDetails/index.js
micro-ui/web/micro-ui-internals/packages/modules/sandbox/src/pages/employee/ProductPage/ProductPageComponent.js
micro-ui/web/micro-ui-internals/packages/modules/sandbox/src/pages/employee/index.js

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

Sandbox UI update 2

---

health/micro-ui/web/microplan/package.json

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

FEATURE/HCMPRE-0000 : To check component export issue 

---

health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/components/HCMMyCampaignRowCard.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/MyCampaignNew.js

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

FEATURE/HCMPRE-0001 : Error fix

---

micro-ui/web/micro-ui-internals/packages/svg-components/package.json
micro-ui/web/micro-ui-internals/packages/svg-components/src/index.js

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

Imported Tutorial Guide svg component

---

health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/Module.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/components/CustomTable.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/pages/employee/L2Main.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/pages/employee/index.js

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

Iccd dev custom table fix

---

health/micro-ui/web/micro-ui-internals/example/src/UICustomizations.js
health/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/healthdss.scss
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/MyCampaignNew.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/package.json
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/Module.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/components/DSSCampaignRowCard.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/components/DSSCard.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/configs/InboxConfig.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/configs/UICustomizations.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/hooks/index.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/hooks/useInboxSearch.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/pages/employee/Inbox.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/pages/employee/index.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/utils/convertEpochToNewDateFormat.js

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

FEATURE/HCMPRE-2869 : Added project search inbox

---

micro-ui/web/micro-ui-internals/packages/modules/workbench/package.json
micro-ui/web/public/index.html

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

UI Changes

---

health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/components/AdvancedMapCharts/HeatMap/HeatMapChart.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/components/CustomBarChart.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/components/CustomHorizontalBarChart.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/components/CustomPieChart.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/components/DateRange.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/components/Filters.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/components/MapChart.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/components/MapDrillChart.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/components/StackedTable.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/components/VennDiagramChart.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/pages/employee/L1Main.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/pages/employee/L2Main.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/utils/getDuration.js

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

added getDuration util in health-dss module

---

health/micro-ui/web/micro-ui-internals/package.json
health/micro-ui/web/micro-ui-internals/packages/css/package.json
health/micro-ui/web/package.json

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

BUGFIX/HCMPRE-2551: CSS PUBLISH FIX

---

health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/BillDetailsTable.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/components/VerifyAndGeneratePaymentsTable.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/pages/employee/bill_payment_details.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-payments/src/pages/employee/my_bills.js

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

Payment verify bills

---

micro-ui/web/micro-ui-internals/packages/modules/core/package.json
micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

Autologin. ccsd-414.sanitation.

---

micro-ui/web/core/package.json
micro-ui/web/micro-ui-internals/example/package.json
micro-ui/web/micro-ui-internals/packages/modules/workbench/CHANGELOG.md
micro-ui/web/micro-ui-internals/packages/modules/workbench/package.json
micro-ui/web/micro-ui-internals/packages/modules/workbench/src/pages/employee/MDMSEdit.js
micro-ui/web/package.json
micro-ui/web/sandbox/package.json
micro-ui/web/workbench/package.json

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

## [1.0.27]  [11-Jul-2025] - Added success toast after editing master data

---

micro-ui/web/micro-ui-internals/example/package.json
micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login-v2/config-v2.js
micro-ui/web/micro-ui-internals/packages/modules/sandbox/CHANGELOG.md
micro-ui/web/micro-ui-internals/packages/modules/sandbox/package.json
micro-ui/web/sandbox/package.json

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

Update config-v2.js removed privacy policy

---

health/micro-ui/web/micro-ui-internals/example/package.json
health/micro-ui/web/micro-ui-internals/package.json
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/package.json

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

ui components: Upgrade @egovernments/digit-ui-components to 0.2.0-beta.48

---

health/micro-ui/web/console/package.json
health/micro-ui/web/microplan/package.json
health/micro-ui/web/package.json

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

FEATURE/HCMPRE-0001 : Build issue check

---

health/micro-ui/web/health-payments/package.json

**JIRA ID**  
**Module**  
---
**JIRA ID**  
**Module**  
---

Build issue fix for Payments-ui

---

health/micro-ui/web/micro-ui-internals/packages/css/package.json

BUGFIX::HCMPRE-0001 :Added the missing css from console updated version

---

micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login-v2/index.js
micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Otp/index.js
micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/SignUp-v2/index.js

Mdmsbanner images

---

micro-ui/web/micro-ui-internals/packages/modules/sandbox/src/pages/employee/ProductDetails/ProductDetailsComponentUpdated.js

added obps and fsm walkthrough

---

micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ForgotOrganizationTooltip.js
micro-ui/web/micro-ui-internals/packages/modules/core/src/components/LoginSignupSelector.js

overlapped fields fixed in login and signup

---

micro-ui/web/micro-ui-internals/packages/modules/sandbox/src/pages/employee/Landing/LandingComponent.js
micro-ui/web/micro-ui-internals/packages/modules/sandbox/src/pages/employee/Landing/SandboxConfig.js
micro-ui/web/micro-ui-internals/packages/modules/sandbox/src/pages/employee/Landing/SupaDemoPlayer.js

replaced youtube video with supademo links

---

health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/components/FilterByCycle.js
health/micro-ui/web/micro-ui-internals/packages/modules/health-dss/src/pages/employee/L2Main.js

Bugfix/hcmpre 0009- Filter By cycle fix

---

health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/package.json
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/components/CampaignSummary.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/components/CampaignUpdateSummary.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/components/CloneCampaignWrapper.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/components/CreateCampaignComponents/NewUploadData.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/components/SelectingBoundariesDuplicate.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/components/UpdateBoundaryWrapper.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/UpdateCampaign.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/deliveryRule/index.js

BUGFIX/HCMPRE-2941 : Boundary Changes Fixes

---

micro-ui/web/micro-ui-internals/example/public/index.html
micro-ui/web/micro-ui-internals/packages/modules/core/src/components/Dialog/LogoutDialog.js
micro-ui/web/micro-ui-internals/packages/modules/sandbox/src/pages/employee/ProductDetails/ProductDetailsComponentUpdated.js
micro-ui/web/public/index.html

fixed ccsd-558,594,562,593

---

micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/sandbox.scss

fixed the tooltip css

---

micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ForgotOrganizationTooltip.js
micro-ui/web/micro-ui-internals/packages/modules/core/src/components/LoginSignupSelector.js

fixed the spacing in login page

---

health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/deliveryRule/AddDeliverycontext.js

ISSUE-2962: delivery value fix

---

health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/components/FiltersRenderer.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/appConfigurationRedesign/DependentFieldsWrapper.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/appConfigurationRedesign/RenderConditionalField.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/utils/appConfigHelpers.js

FEATURE-2972:: Assessment Checklist and Feature Properties

---

health/micro-ui/web/health-dss/package.json

Upgrading digit-ui-module-core package for Dss

BUGFIX/HCMPRE-1129: Upgrading digit-ui-module-core package for Dss

---

micro-ui/web/public/index.html

Matomo code changes for sandbox screens

---

health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/components/FiltersRenderer.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/appConfigurationRedesign/DependentFieldsWrapper.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/utils/appConfigHelpers.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/utils/template_components/RegistrationComponents.js

Demo fixes for v 0.5

---

health/micro-ui/web/micro-ui-internals/example/public/index.html
health/micro-ui/web/micro-ui-internals/example/webpack.config.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/appConfigurationRedesign/AppConfigurationWrapper.js
health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/appConfigurationRedesign/RenderConditionalField.js

- **Local development not working fix**
- **min max validation remove**
**JIRA ID**  
**Module**  

console fix

---

micro-ui/web/micro-ui-internals/example/public/index.html
micro-ui/web/public/index.html

Removed matomo cloud and updated url to be taken from blobal configs

---

micro-ui/web/micro-ui-internals/packages/modules/core/package.json
micro-ui/web/micro-ui-internals/packages/modules/workbench/package.json

react comp version updated in core and workbench

---

health/micro-ui/web/micro-ui-internals/packages/modules/campaign-manager/src/pages/employee/deliveryRule/index.js

Fixed delivery rule initialization issue.
